### ISSUE TITLE
Why trim?

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/condense-whitespace#1]
We can just run `trim()` ourselves. It's the repeating whitespace that's annoying to write.

Maybe also provide two methods:
- `standard()`, using `\s`
- `all()`, using [whitespace-regex](https://www.npmjs.com/whitespace-regex)

If you're not interested, lemme know and I'll write a "normalize-whitespace" package -- but it'd be best not to as there're already enough whitespace packages.

**Comment by sindresorhus** [comment]
Why not? Is the `.trim()` problematic for you?

**Comment by stevenvachon** [comment]
Yes, I only want to remove repeating whitespace. I need to preserve leading/trailing space and in some cases use `trimLeft()` and `trimRight()`.

**Comment by sindresorhus** [comment]
I like the default trim behavior as that's my most common use-case, but happy to accept a PR that adds a `trim` option as the second argument.

**Comment by stevenvachon** [comment]
I realize now that I need a special type of normalization for HTML where certain whitespace characters are not removed. Meaning that I will have to publish a new package, anyway. I won't be writing the PR that you speak of, unfortunately. Maybe keep this open for others to comment/volunteer?

**Comment by sindresorhus** [comment]
Nah
