### ISSUE TITLE
support String object?

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/condense-whitespace#2]
For completeness:

``` js
console.log( typeof new String() );  //=> "object"
```

**Comment by sindresorhus** [comment]
Why? Do you actually need that?

**Comment by stevenvachon** [comment]
Nope, I don't. Just pointing it out. By the way, your "trim-left" and "trim-right" packages don't have type checks -- perhaps this one shouldn't either.

**Comment by sindresorhus** [comment]
Doesn't matter. Nobody should be using String objects. Even if I change it here they're in a world of hurt elsewhere.
